# SCM-INSIGHTS constants (aligned with main backend for Directory/Suppliers)
from datetime import datetime, timedelta, timezone

COUNTRY_NAMES = []  # Optional: populate if needed for signup/login response

# License validity
DAY, WEEK, MONTH, YEAR = "Day", "Week", "Month", "Year"
VALIDITY_DICT = {DAY: 1, WEEK: 7, MONTH: 30, YEAR: 365}


def get_valid_till_date(start_time, period, validity_days):
    if validity_days is None and period is None:
        return start_time
    if validity_days is not None:
        return start_time + timedelta(days=validity_days)
    return start_time + timedelta(days=VALIDITY_DICT.get(period, 365)) if period else datetime.max.replace(tzinfo=timezone.utc)

SUPPLIER_COUNTRIES = [
    "AFGHANISTAN", "ALBANIA", "ALGERIA", "AMERICAN SAMOA", "ANDORRA", "ANGOLA",
    "ANGUILLA", "ANTIGUA AND BARBUDA", "ARGENTINA", "ARMENIA", "ARUBA", "AUSTRALIA",
    "AUSTRIA", "AZERBAIJAN", "BAHAMAS", "BAHRAIN", "BANGLADESH", "BARBADOS", "BELARUS",
    "BELGIUM", "BELIZE", "BENIN", "BERMUDA", "BHUTAN", "BOLIVIA", "BOSNIA AND HERZEGOVINA",
    "BOTSWANA", "BRAZIL", "BRITISH INDIAN OCEAN TERRITORY", "BRITISH VIRGIN ISLANDS",
    "BRUNEI", "BULGARIA", "BURKINA FASO", "BURUNDI", "CAMBODIA", "CAMEROON", "CANADA",
    "CAPE VERDE", "CAYMAN ISLANDS", "CHAD", "CHILE", "CHINA", "CHINA HONG KONG", "CHINA MACAU",
    "CHINA TAIWAN", "COATE DE IVOIRE", "COLOMBIA", "COMOROS", "CONGO", "COSTA RICA",
    "CROATIA", "CUBA", "CURACAO", "CYPRUS", "CZECH", "DEMOCRATIC CONGO", "DENMARK",
    "DJIBOUTI", "DOMINICA", "EAST TIMOR", "ECUADOR", "EGYPT", "EL SALVADOR",
    "EQUATORIAL GUINEA", "ESTONIA", "ETHIOPIA", "EUROPEAN UNION", "FAROE ISLANDS", "FIJI",
    "FINLAND", "FRANCE", "FRENCH GUYANA", "FRENCH POLYNESIA", "GABON", "GAMBIA", "GEORGIA",
    "GERMANY", "GHANA", "GIBRALTAR", "GREECE", "GREENLAND", "GRENADA", "GUADELOUPE", "GUAM",
    "GUATEMALA", "GUINEA", "GUINEA BISSAU", "GUYANA", "HAITI", "HONDURAS", "HUNGARY",
    "ICELAND", "INDIA", "INDONESIA", "IRAN", "IRAQ", "IRELAND", "ISRAEL", "ITALY", "JAMAICA",
    "JAPAN", "JERSEY", "JORDAN", "KAZAKHSTAN", "KENYA", "KIRIBATI", "KOSOVO", "KUWAIT",
    "KYRGYZSTAN", "LAOS", "LATVIA", "LEBANON", "LESOTHO", "LIBERIA", "LIBYA", "LIECHTENSTEIN",
    "LITHUANIA", "LUXEMBOURG", "MACEDONIA", "MADAGASCAR", "MALAWI", "MALAYSIA", "MALDIVES",
    "MALI", "MALTA", "MARSHALL ISLANDS", "MARTINIQUE", "MAURITANIA", "MAURITIUS", "MAYOTTE",
    "MEXICO", "MOLDOVA", "MONACO", "MONGOLIA", "MONTENEGRO", "MONTSERRAT", "MOROCCO",
    "MOZAMBIQUE", "MYANMAR", "NAMIBIA", "NAURU", "NEPAL", "NETHERLANDS", "NEW CALEDONIA",
    "NEW ZEALAND", "NICARAGUA", "NIGER", "NIGERIA", "NORTH KOREA", "NORTH MARIANA ISLANDS",
    "NORWAY", "OMAN", "PAKISTAN", "PALESTINE", "PANAMA", "PAPUA NEW GUINEA", "PARAGUAY",
    "PERU", "PHILIPPINES", "POLAND", "PORTUGAL", "PUERTO RICO", "QATAR", "REUNION", "ROMANIA",
    "RUSSIA", "RWANDA", "SAINT BARTHELEMY", "SAINT HELENA", "SAINT KITTS AND NEVIS", "SAINT LUCIA",
    "SAINT MARTIN", "SAINT VINCENT AND THE GRENADINES", "SAMOA", "SAN MARINO", "SAUDI ARABIA",
    "SENEGAL", "SERBIA", "SEYCHELLES", "SIERRA LEONE", "SINGAPORE", "SLOVAKIA", "SLOVENIA",
    "SOLOMON ISLANDS", "SOMALIA", "SOUTH AFRICA", "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
    "SOUTH KOREA", "SOUTH SUDAN", "SPAIN", "SRI LANKA", "SUDAN", "SURINAME", "SWAZILAND",
    "SWEDEN", "SWITZERLAND", "SYRIA", "TAJIKISTAN", "TANZANIA", "THAILAND",
    "THE CENTRAL AFRICAN REPUBLIC", "THE DOMINICAN REPUBLIC", "THE FEDERATED STATES OF MICRONESIA",
    "THE UNITED ARAB EMIRATES", "TOGO", "TONGA", "TRINIDAD AND TOBAGO", "TUNISIA", "TURKEY",
    "TURKMENISTAN", "TURKS AND CAICOS ISLANDS", "UGANDA", "UKRAINE", "UNITED KINGDOM",
    "UNITED STATES", "UNITED STATES VIRGIN ISLANDS", "URUGUAY", "UZBEKISTAN", "VANUATU",
    "VENEZUELA", "VIETNAM", "WESTERN SAHARA", "YEMEN", "ZAMBIA", "ZIMBABWE",
]
